# Generated by Django 3.1 on 2020-09-08 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('guid', models.TextField()),
                ('url', models.URLField()),
                ('outcome_url', models.URLField()),
                ('client_id', models.TextField()),
                ('client_secret', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LTIUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_lms_guid', models.TextField()),
                ('lms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lti.lms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LTICourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_lms_guid', models.TextField()),
                ('lms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lti.lms')),
            ],
        ),
    ]
