name: Python package

on:
  push:
    branches:
      - '*'
      - '*/*'
  pull_request:
    branches:
      - '*'
      - '*/*'
  schedule:
    - cron:  '0 6 * * 1'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: django
          POSTGRES_PASSWORD: django_password
          POSTGRES_DB: django_platon
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
  
    name: Python 3.8
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: 'x64'

      - name: Install the Sandbox
        run : |
          git clone https://github.com/PremierLangage/sandbox.git
          cd sandbox/
          ./bin/install.sh
          python3 manage.py runserver 7000 &> /dev/null &
          cd ..

      - name: Install Platon Server
        run: |
          ./bin/install.sh

      - name: Run redis
        run: ./bin/redis_docker.sh

      - name: Run Tox
        run: tox

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml